version: '3'
services:
  be:
    build: ./BE/zeepseek
    container_name: backend_container
    ports:
      - "8081:8081"
    environment:
      - MYSQL_HOST=host.docker.internal
      - MONGO_HOST=mongodb
      - ELASTICSEARCH_HOST=elasticsearch
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGODB_URI=${MONGODB_URI}
      - ES_USERNAME=${ES_USERNAME}
      - ES_PASSWORD=${ES_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    networks:
      - e203

  fe:
    build: ./FE
    container_name: frontend_container
    # fe 서비스는 내부에서 5173 포트를 사용 (Vite 빌드 결과물을 serve 명령으로 서빙)
    expose:
      - "5173"
    restart: always
    networks:
      - e203

  recommend:
    build: ./ML
    container_name: recommend_container
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=host.docker.internal
      - MONGO_HOST=host.docker.internal
      - ES_HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    networks:
      - e203

networks:
  e203:
    external: true